name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron:  '45 6 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate

      - name: Lint PHP
        run: |
          find src/ tests/ -name '*.php' -print0 | xargs -0 -n1 -P4 php -dxdebug.mode=off -l >/dev/null

      - name: Install dependencies
        if: ${{ matrix.php <= '8.1' }}
        run: composer install --prefer-dist --no-progress --ansi

      - name: Install dependencies PHP 8.2
        # @todo: Needed until prophecy (req by phpunit) allows PHP 8.2, https://github.com/phpspec/prophecy/issues/556
        if: ${{ matrix.php > '8.1' }}
        run: composer install --prefer-dist --no-progress --ansi --ignore-platform-req=php+

      - name: Run test suite
        run: composer run-script test
